name: Validate templates (PR)

on:
  pull_request:
    branches:
      - main

jobs:
  get_params:
    name: Get validation parameters
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      all_changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
      any_changed: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          dir_names: true
          dir_names_exclude_current_dir: true
          json: true
          files_ignore: |
            .github/**/*
            **/*.md

  validate_template:
    needs: get_params
    name: Deploy templates
    runs-on: ubuntu-latest
    if: ${{ needs.get_params.outputs.any_changed }}
    strategy:
      fail-fast: false
      matrix:
        template: ${{ fromJson(needs.get_params.outputs.all_changed_files) }}
    steps:
      - name: Checkout files
        uses: actions/checkout@v3
      - name: Use Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Validate template
        run: terraform plan -var "vault_role_id="$VAULT_ROLE_ID"" -var "vault_secret_id="$VAULT_SECRET_ID""
        working-directory: ./${{ matrix.template }}
        env:
            VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID }}
            VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}